<a href="https://colab.research.google.com/github/elewin2022/Data_Sci/blob/main/Ethan_Lewin_Copy_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [ ]:
for i in range(100): #anything within in range of 100 exluding ten, this will pick a random number 0-99 (100 numbers)
    print(i) #setting range of numbers

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [ ]:
for i in range(5,8): #setting range between 5 and 8, excluding 8
    print(i)

5
6
7


In [ ]:
for i in range(3): #setting range between 0-3, excluding 3, printing the words Test Number before
    print( "Test Number: " , i ) #you can add a string to the range and have that printed w/ the result

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [ ]:
def square(x):#function always starts with def, everything within definition of function gets tabed in
    return x**2 #defining what function will be used and setting its parameters 

In [ ]:
square(5) #demonstrating the function 

25

In [ ]:
square(square(2)) #two to the third power, but doing so using the function 

16

In [ ]:
square(square(square(2))) #same thing, just two raised to the power of 4


256

In [ ]:
square(123456) #demonstrating squaring a large number using the function 

15241383936

In [ ]:
square(square(5)) #using the function to get 5x5=25, 25x25=625

625

In [ ]:
def add_two(x): #creating a function to give x+2
    return x+2

In [ ]:
add_two(5) #5 is x in this case, 5+2=7

7

In [ ]:
square(add_two(5)) #add 2 to x which is 5 = 7, 7x7 or 7 squared = 49

49

### Logical Branching

In [ ]:
choice = "apple" #setting a variable to a word

In [ ]:
if choice == "apple": #if you choose apple it prints it will display that you chose apple and if not, it will display that you did not choose apple

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You choose apples.


In [ ]:
choice = "orange" #setting variable to word orange

In [ ]:
if choice == "apple": #listed twice, testing 

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [ ]:
choice = "apple" #setting variable to word apple

In [ ]:
if choice == "apple": #adding printed sayings to the function (adding more options and a third option, no apples or oranges)

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [ ]:
choice = input("Please enter your choice (i.e. apple): ") #this gives us the option to choose apple or orange when prompted 

Please enter your choice (i.e. apple): apple


In [ ]:
choice #when run choice, it lists input choice, so in my case I put in orange and it listed orange

'apple'

In [ ]:
if choice == "apple": #if you do not choose apple or oranges, it gives you neither, it gives you your choice if spelled correctly

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You choose apples.


#### Coins

In [ ]:
import numpy as np #need to import numpy as np first

In [ ]:
np.random.random() #random number integer generator (randint gives a whole number) 

0.02572950573120114

In [ ]:
np.random.random() > 0.5 #choose a random number and if over 0.5 it will give you either true or false (can't tell which one right now) 

False

In [ ]:
def flip_coin(): # creating a function that produces heads if over 0.5 and tails under 0.5 (assigns Heads to number greater than 0.5) 
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")

In [ ]:
flip_coin() #running the function 

Heads


### Graphics Output

In [ ]:
from IPython.core.display import display, HTML #importing IPython.core.display 

In [ ]:
display(HTML('<h1>Hello, world!</h1>')) #printing the function to write "Hello, world!" (displays Hello, world! from the Ipython.core.display)

In [ ]:
def coin(): #give us a number either zero or 1, sets parameters of range for coin zero to 2 excluding 2
  return np.random.randint(2)

In [ ]:
coin() #running the function, will display zero to one 

0

In [ ]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">')) #displaying image for heads 

In [ ]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg' #showing the links to images for heads and tails
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'

In [ ]:
def show_img(img): #creating the function to show the image of heads or tails 
  display(HTML('<img src=' + img + '>'))

In [ ]:
show_img(heads) #showing heads

In [ ]:
show_img(tails) #showing tails

In [ ]:
def flip_coin(): #defines coin flip function for heads or tails

    if coin():
        show_img(heads)
    else:
        show_img(tails)

In [ ]:
flip_coin() #demonstrates function

In [ ]:
for i in range(5): #range of coins, listing 5 coins, flips 5 coins and displays results
    flip_coin()

In [ ]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

In [ ]:
def shuffle(x): #creating the function to shuffle, define function 
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [ ]:
a = np.arange(52) #assings variable a to a range of 0-52, excluding 52

In [ ]:
shuffle(a) #shuffling range a displaying numbers 0-52 in random order 

array([34, 23, 14,  1, 15, 45, 17, 51, 33, 26, 11, 18, 20,  0,  3,  8, 19,
       30, 10, 28, 41, 47, 12, 31, 13, 48, 27, 25, 49, 38, 40, 35,  7, 37,
       24, 21, 29, 22,  9, 50, 43, 46, 16,  5,  2, 42,  4, 39,  6, 32, 44,
       36])

In [ ]:
np.random.permutation(52) #this generators a sequence of random numbers 0-52, excluding 52

array([ 3, 42,  2,  9, 39, 34, 35,  8, 36,  7,  5, 26, 25,  1, 11, 44, 22,
        0, 28, 50, 32, 37, 40, 20, 23, 14,  6, 30, 19, 38, 47, 12, 43, 41,
       10, 51, 45, 29, 33, 31,  4, 17, 16, 18, 15, 48, 13, 27, 21, 46, 49,
       24])

### Speed Test

In [ ]:
%%timeit 
shuffle(a) #how many times a can be shuffled 

175 µs ± 604 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
%%timeit
np.random.permutation(52) #random shuffle of sequence 

In [ ]:
import numpy as np #import numpy as np

In [ ]:
np.random.permutation(52) #this generators a sequence of random numbers 0-52, excluding 52

array([ 1, 11, 36, 29,  8, 37, 12, 51,  3, 33, 50, 47, 28, 44, 45, 19, 18,
       16, 32, 22,  9, 34,  5, 13, 40,  4, 31, 42, 30, 35, 27, 39, 10, 20,
       23, 14, 15, 26, 49,  2, 48, 46, 43,  7, 41, 24, 21, 38, 17,  6, 25,
        0])

In [ ]:
cards = np.random.permutation(52)#sets cards to random permutation

In [ ]:
cards #displays cards from above function

array([41, 34, 19, 40, 39,  5, 22,  6, 35, 14,  8, 29,  1,  4, 15, 16, 27,
       37, 13,  7, 36, 43, 12,  0, 51, 30, 28, 42,  2, 49, 23, 31, 25,  3,
       24, 11, 17, 26, 47, 33, 20, 50, 21, 48,  9, 46, 18, 32, 10, 45, 44,
       38])

In [ ]:
cards[0]#displays random card selected from spot 1

41

In [ ]:
cards[1] #displays random card selected from spot 2

34

In [ ]:
cards[2]#displays random card selected from spot 3

19

In [ ]:
#these are the cards that will be assigned to a number within the array

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [ ]:
np.arange(52).reshape(4,13) #arranges cards and reshapes them

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [ ]:
np.arange(52).reshape(4,13)%13 #arranges cards, reshapes them, and divides em into groups of 13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
np.arange(52).reshape(4,13)//13 #arranges cards, reshapes em, and double divides em

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [ ]:
suits = ['Clubs','Spades','Hearts','Diamonds'] #defines suits
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King'] #setting variable to numbers and faces

In [ ]:
def card_name(card_number): #defining card name and number in a function
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [ ]:
card_name(0) #displays card number and suit of card chosen

'Ace of Clubs'

In [ ]:
card_name(51) #displays card number and suit of card chosen

'King of Diamonds'

In [ ]:
cards = np.random.permutation(52) #this generators a sequence of random numbers 0-52, excluding 52

In [ ]:
top_of_deck         = card_name(cards[0]) #assigns names to card in order
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [ ]:
top_of_deck, second_card_in_deck, last_card_in_deck #testing the above function

('Jack of Diamonds', 'Five of Spades', 'Jack of Hearts')

In [ ]:
for i in range(5): #print 5 different cards
    print(card_name(cards[i]))

Jack of Diamonds
Five of Spades
Three of Diamonds
Ten of Diamonds
Four of Spades


In [ ]:
for i in range(15): #print 15 different cards
    print(card_name(cards[i]))

Jack of Diamonds
Five of Spades
Three of Diamonds
Ten of Diamonds
Four of Spades
Six of Spades
Ten of Spades
Ten of Hearts
Seven of Clubs
Seven of Diamonds
Five of Diamonds
Eight of Hearts
Ace of Hearts
King of Diamonds
Nine of Diamonds


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [ ]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/" #setting a variable a url for heads and then tails
card_url_tail = ".png"

In [ ]:
suit = ['k','p','s','l'] #assigns variables to suit and then sets variable to card
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [ ]:
i = np.random.randint(4) #creating variables equal to random whole numbers using randint
j = np.random.randint(13)

In [ ]:
i,j #listing i and j

(2, 1)

In [ ]:
suit[i] #picks random whole number from above

's'

In [ ]:
card[j] #""

'2'

In [ ]:
from IPython.core.display import display, HTML #import IPython.core.display

In [ ]:
def show_img(img): #creating the function to show and image (displays card image)
  display(HTML('<img src=' + img + '>'))

In [ ]:
img = card_url_head + suit[i] + card[j] + card_url_tail #setting image equal to urls/ suits/ card

In [ ]:
show_img(img) #showing random card 

In [ ]:
def card_image(card_number): #creating the function to show a random card image and card number
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [ ]:
card_image(3) #listing what will become image

'k4'

In [ ]:
img = card_url_head + card_image(3) + card_url_tail #setting image to links from above

In [ ]:
show_img(img) #displaying card 

In [ ]:
for i in range(52): #displaying function to display cards 0-52
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)